const URUN_KIND = {
  1: { name: "Power", tr: "Enerji", file: "power" },
  2: { name: "Water", tr: "Su", file: "water" },
  3: { name: "Apples", tr: "Elmalar", file: "apples" },
  4: { name: "Oranges", tr: "Portakallar", file: "oranges" },
  5: { name: "Grapes", tr: "Üzümler", file: "grapes" },
  6: { name: "Grain", tr: "Tahıl", file: "grain" },
  7: { name: "Steak", tr: "Biftek", file: "steak" },
  8: { name: "Sausages", tr: "Sosis", file: "sausages" },
  9: { name: "Eggs", tr: "Yumurtalar", file: "eggs" },
  10: { name: "Crude Oil", tr: "Ham Petrol", file: "crude-oil" },
  11: { name: "Petrol", tr: "Benzin", file: "petrol" },
  12: { name: "Diesel", tr: "Dizel", file: "diesel" },
  13: { name: "Transport", tr: "Nakliye", file: "transport" },
  14: { name: "Minerals", tr: "Mineraller", file: "minerals" },
  15: { name: "Bauxite", tr: "Boksit", file: "bauxite" },
  16: { name: "Silicon", tr: "Silisyum", file: "silicon" },
  17: { name: "Chemicals", tr: "Kimyasallar", file: "chemicals" },
  18: { name: "Aluminium", tr: "Alüminyum", file: "aluminium" },
  19: { name: "Plastic", tr: "Plastik", file: "plastic" },
  20: { name: "Processors", tr: "İşlemciler", file: "processors" },
  21: { name: "Electronic Components", tr: "Elektronik Bileşenler", file: "electronic-components" },
  22: { name: "Batteries", tr: "Piller", file: "batteries" },
  23: { name: "Displays", tr: "Ekranlar", file: "displays" },
  24: { name: "Smart Phones", tr: "Akıllı Telefonlar", file: "smart-phones" },
  25: { name: "Tablets", tr: "Tabletler", file: "tablets" },
  26: { name: "Laptops", tr: "Dizüstü Bilgisayarlar", file: "laptops" },
  27: { name: "Monitors", tr: "Monitörler", file: "monitors" },
  28: { name: "Televisions", tr: "Televizyonlar", file: "televisions" },
  29: { name: "Plant Research", tr: "Bitki Araştırması", file: "plant-research" },
  30: { name: "Energy Research", tr: "Enerji Araştırması", file: "energy-research" },
  31: { name: "Mining Research", tr: "Madencilik Araştırması", file: "mining-research" },
  32: { name: "Electronics Research", tr: "Elektronik Araştırması", file: "electronics-research" },
  33: { name: "Breeding Research", tr: "Yetiştirme Araştırması", file: "breeding-research" },
  34: { name: "Chemistry Research", tr: "Kimya Araştırması", file: "chemistry-research" },
  35: { name: "Software", tr: "Yazılım", file: "software" },
  40: { name: "Cotton", tr: "Pamuk", file: "cotton" },
  41: { name: "Fabric", tr: "Kumaş", file: "fabric" },
  42: { name: "Iron Ore", tr: "Demir Cevheri", file: "iron-ore" },
  43: { name: "Steel", tr: "Çelik", file: "steel" },
  44: { name: "Sand", tr: "Kum", file: "sand" },
  45: { name: "Glass", tr: "Cam", file: "glass" },
  46: { name: "Leather", tr: "Deri", file: "leather" },
  47: { name: "On-board Computer", tr: "Araç Bilgisayarı", file: "on-board-computer" },
  48: { name: "Electric Motor", tr: "Elektrik Motoru", file: "electric-motor" },
  49: { name: "Luxury Car Interior", tr: "Lüks Araç İç Donanımı", file: "luxury-car-interior" },
  50: { name: "Car Interior", tr: "Araç İç Donanımı", file: "car-interior" },
  51: { name: "Car Body", tr: "Araç Kasası", file: "car-body" },
  52: { name: "Combustion Engine", tr: "İçten Yanmalı Motor", file: "combustion-engine" },
  53: { name: "Economy E-Car", tr: "Ekonomik E-Araba", file: "economy-e-car" },
  54: { name: "Luxury E-Car", tr: "Lüks E-Araba", file: "luxury-e-car" },
  55: { name: "Economy Car", tr: "Ekonomik Araba", file: "economy-car" },
  56: { name: "Luxury Car", tr: "Lüks Araba", file: "luxury-car" },
  57: { name: "Truck", tr: "Kamyon", file: "truck" },
  58: { name: "Automotive Research", tr: "Otomotiv Araştırması", file: "automotive-research" },
  59: { name: "Fashion Research", tr: "Moda Araştırması", file: "fashion-research" },
  60: { name: "Underwear", tr: "İç Çamaşırı", file: "underwear" },
  61: { name: "Gloves", tr: "Eldivenler", file: "gloves" },
  62: { name: "Dress", tr: "Elbise", file: "dress" },
  63: { name: "Simmi Shoes", tr: "Simmi Ayakkabılar", file: "simmi-shoes" },
  64: { name: "Handbags", tr: "El Çantaları", file: "handbags" },
  65: { name: "Sneakers", tr: "Spor Ayakkabılar", file: "sneakers" },
  66: { name: "Seeds", tr: "Tohumlar", file: "seeds" },
  67: { name: "Xmas Crackers", tr: "Yılbaşı Çıtlatıcıları", file: "xmas-crackers" },
  68: { name: "Gold Ore", tr: "Altın Cevheri", file: "gold-ore" },
  69: { name: "Golden Bars", tr: "Altın Külçeler", file: "golden-bars" },
  70: { name: "Gold Watch", tr: "Altın Saat", file: "gold-watch" },
  71: { name: "Necklace", tr: "Kolye", file: "necklace" },
  72: { name: "Sugarcane", tr: "Şeker Kamışı", file: "sugarcane" },
  73: { name: "Ethanol", tr: "Etanol", file: "ethanol" },
  74: { name: "Methane", tr: "Metan", file: "methane" },
  75: { name: "Carbon Fiber", tr: "Karbon Fiber", file: "carbon-fiber" },
  76: { name: "Carbon Composite", tr: "Karbon Kompozit", file: "carbon-composite" },
  77: { name: "Fuselage", tr: "Gövde", file: "fuselage" },
  78: { name: "Wing", tr: "Kanat", file: "wing" },
  79: { name: "High-Grade E-Components", tr: "Yüksek Kalite E-Bileşenler", file: "high-grade-e-components" },
  80: { name: "Flight Computer", tr: "Uçuş Bilgisayarı", file: "flight-computer" },
  81: { name: "Cockpit", tr: "Kokpit", file: "cockpit" },
  82: { name: "Attitude Control", tr: "Yön Kontrolü", file: "attitude-control" },
  83: { name: "Rocket Fuel", tr: "Roket Yakıtı", file: "rocket-fuel" },
  84: { name: "Fuel Tank", tr: "Yakıt Deposu", file: "fuel-tank" },
  85: { name: "Solid Rocket", tr: "Katı Roket", file: "solid-rocket" },
  86: { name: "Rocket Engine", tr: "Roket Motoru", file: "rocket-engine" },
  87: { name: "Heat Shield", tr: "Isı Kalkanı", file: "heat-shield" },
  88: { name: "Ion Drive", tr: "İyon İticisi", file: "ion-drive" },
  89: { name: "Jet Engine", tr: "Jet Motoru", file: "jet-engine" },
  98: { name: "Quadcopter", tr: "Dört Pervaneli Drone", file: "quadcopter" },
  100: { name: "Aero Research", tr: "Havacılık Araştırması", file: "aero-research" },
  101: { name: "Reinforced Concrete", tr: "Betonarme", file: "reinforced-concrete" },
  102: { name: "Bricks", tr: "Tuğlalar", file: "bricks" },
  103: { name: "Cement", tr: "Çimento", file: "cement" },
  104: { name: "Clay", tr: "Kil", file: "clay" },
  105: { name: "Limestone", tr: "Kireçtaşı", file: "limestone" },
  106: { name: "Wood", tr: "Odun", file: "wood" },
  107: { name: "Steel Beams", tr: "Çelik Kirişler", file: "steel-beams" },
  108: { name: "Planks", tr: "Tahta Levhalar", file: "planks" },
  109: { name: "Windows", tr: "Pencereler", file: "windows" },
  110: { name: "Tools", tr: "Aletler", file: "tools" },
  111: { name: "Construction Units", tr: "İnşaat Birimleri", file: "construction-units" },
  112: { name: "Bulldozer", tr: "Buldozer", file: "bulldozer" },
  113: { name: "Materials Research", tr: "Malzeme Araştırması", file: "materials-research" },
  114: { name: "Robots", tr: "Robotlar", file: "robots" },
  115: { name: "Cow", tr: "İnek", file: "cow" },
  116: { name: "Pig", tr: "Domuz", file: "pig" },
  117: { name: "Milk", tr: "Süt", file: "milk" },
  118: { name: "Coffee Beans", tr: "Kahve Çekirdekleri", file: "coffee-beans" },
  119: { name: "Coffee Ground", tr: "Öğütülmüş Kahve", file: "coffee-ground" },
  120: { name: "Vegetables", tr: "Sebzeler", file: "vegetables" },
  121: { name: "Bread", tr: "Ekmek", file: "bread" },
  122: { name: "Cheese", tr: "Peynir", file: "cheese" },
  123: { name: "Apple Pie", tr: "Elmalı Turta", file: "apple-pie" },
  124: { name: "Orange Juice", tr: "Portakal Suyu", file: "orange-juice" },
  125: { name: "Apple Cider", tr: "Elma Şarabı", file: "apple-cider" },
  126: { name: "Ginger Beer", tr: "Zencefilli Bira", file: "ginger-beer" },
  127: { name: "Pizza", tr: "Pizza", file: "pizza" },
  128: { name: "Pasta", tr: "Makarna", file: "pasta" },
  129: { name: "Hamburger", tr: "Hamburger", file: "hamburger" },
  130: { name: "Lasagna", tr: "Lazanya", file: "lasagna" },
  131: { name: "Meatballs", tr: "Köfteler", file: "meatballs" },
  132: { name: "Cocktails", tr: "Kokteyller", file: "cocktails" },
  133: { name: "Flour", tr: "Un", file: "flour" },
  134: { name: "Butter", tr: "Tereyağı", file: "butter" },
  135: { name: "Sugar", tr: "Şeker", file: "sugar" },
  136: { name: "Cocoa Beans", tr: "Kakao Çekirdekleri", file: "cocoa-beans" },
  137: { name: "Dough", tr: "Hamur", file: "dough" },
  138: { name: "Gravy Boat", tr: "Sos Teknesi", file: "gravy-boat" },
  139: { name: "Fodder", tr: "Yem", file: "fodder" },
  140: { name: "Chocolate", tr: "Çikolata", file: "chocolate" },
  141: { name: "Vegetable Oil", tr: "Bitkisel Yağ", file: "vegetable-oil" },
  142: { name: "Salad", tr: "Salata", file: "salad" },
  143: { name: "Samosas", tr: "Samosalar", file: "samosas" },
  144: { name: "Xmas Ornament", tr: "Yılbaşı Süsü", file: "xmas-ornament" },
  145: { name: "Recipes", tr: "Tarifler", file: "recipes" },
  146: { name: "Pumpkin", tr: "Balkabağı", file: "pumpkin" },
  147: { name: "Jack-o-Lantern", tr: "Jack-o-Lantern", file: "jack-o-lantern" },
  148: { name: "Witch Costume", tr: "Cadı Kostümü", file: "witch-costume" },
  149: { name: "Pumpkin Soup", tr: "Balkabağı Çorbası", file: "pumpkin-soup" },
  150: { name: "Tree", tr: "Ağaç", file: "tree" },
  151: { name: "Easter Bunny", tr: "Paskalya Tavşanı", file: "easter-bunny" },
  152: { name: "Ramadan Sweets", tr: "Ramazan Tatlıları", tr2: "Ramazan Şekeri", file: "ramadan-sweets" },
  153: { name: "Ice Cream Chocolate", tr: "Çikolatalı Dondurma", file: "icecream-chocolate" },
  154: { name: "Ice Cream Apple", tr: "Elmalı Dondurma", file: "icecream-apple" },
  155: { name: "Cream Egg", tr: "Kremalı Yumurta", file: "cream-egg" },
};
