// ═══════════════════════════════════════════════════════════════
// RECIPES DATA — recipes.json'u global olarak kullanılabilir hale getirir
// ═══════════════════════════════════════════════════════════════

const recipes = [
  // Temel Kaynaklar
  { id: 1, name: "Power" },
  { id: 2, name: "Water" },
  { id: 13, name: "Transport" },
  
  // Tarım
  { id: 66, name: "Seeds" },
  { id: 3, name: "Apples" },
  { id: 4, name: "Oranges" },
  { id: 5, name: "Grapes" },
  { id: 6, name: "Grain" },
  { id: 115, name: "Cows" },
  { id: 116, name: "Pigs" },
  { id: 118, name: "Coffee beans" },
  { id: 120, name: "Vegetables" },
  { id: 139, name: "Fodder" },
  { id: 40, name: "Cotton" },
  { id: 72, name: "Sugarcane" },
  { id: 136, name: "Cocoa" },
  { id: 146, name: "Pumpkin" },
  
  // Gıda
  { id: 7, name: "Steak" },
  { id: 8, name: "Sausages" },
  { id: 9, name: "Eggs" },
  { id: 119, name: "Coffee powder" },
  { id: 117, name: "Milk" },
  { id: 124, name: "Orange juice" },
  { id: 125, name: "Apple cider" },
  { id: 126, name: "Ginger beer" },
  { id: 140, name: "Chocolate" },
  { id: 135, name: "Sugar" },
  { id: 137, name: "Dough" },
  { id: 138, name: "Sauce" },
  { id: 133, name: "Flour" },
  { id: 121, name: "Bread" },
  { id: 123, name: "Apple pie" },
  { id: 127, name: "Frozen pizza" },
  { id: 128, name: "Pasta" },
  { id: 134, name: "Butter" },
  { id: 122, name: "Cheese" },
  { id: 129, name: "Hamburger" },
  { id: 130, name: "Lasagna" },
  { id: 131, name: "Meat balls" },
  { id: 132, name: "Cocktails" },
  { id: 141, name: "Vegetable oil" },
  { id: 142, name: "Salad" },
  { id: 143, name: "Samosa" },
  { id: 149, name: "Pumpkin soup" },
  
  // İnşaat
  { id: 101, name: "Reinforced concrete" },
  { id: 102, name: "Bricks" },
  { id: 108, name: "Planks" },
  { id: 111, name: "Construction units" },
  { id: 104, name: "Clay" },
  { id: 106, name: "Wood" },
  { id: 103, name: "Cement" },
  { id: 105, name: "Limestone" },
  { id: 107, name: "Steel beams" },
  { id: 109, name: "Windows" },
  { id: 110, name: "Tools" },
  
  // Moda
  { id: 41, name: "Fabric" },
  { id: 46, name: "Leather" },
  { id: 60, name: "Underwear" },
  { id: 61, name: "Gloves" },
  { id: 62, name: "Dress" },
  { id: 63, name: "Stiletto Heel" },
  { id: 64, name: "Handbags" },
  { id: 65, name: "Sneakers" },
  { id: 70, name: "Luxury watch" },
  { id: 71, name: "Necklace" },
  
  // Enerji
  { id: 10, name: "Crude oil" },
  { id: 11, name: "Petrol" },
  { id: 12, name: "Diesel" },
  { id: 73, name: "Ethanol" },
  { id: 74, name: "Methane" },
  { id: 83, name: "Rocket fuel" },
  
  // Elektronik
  { id: 20, name: "Processors" },
  { id: 21, name: "Electronic components" },
  { id: 22, name: "Batteries" },
  { id: 23, name: "Displays" },
  { id: 24, name: "Smart phones" },
  { id: 25, name: "Tablets" },
  { id: 26, name: "Laptops" },
  { id: 27, name: "Monitors" },
  { id: 28, name: "Televisions" },
  { id: 114, name: "Robots" },
  { id: 79, name: "High grade e-comps" },
  { id: 98, name: "Quadcopter" },
  { id: 112, name: "Bulldozer" },
  
  // Otomotiv
  { id: 47, name: "On-board computer" },
  { id: 48, name: "Electric motor" },
  { id: 49, name: "Luxury car interior" },
  { id: 50, name: "Basic interior" },
  { id: 51, name: "Car body" },
  { id: 52, name: "Combustion engine" },
  { id: 53, name: "Economy e-car" },
  { id: 54, name: "Luxury e-car" },
  { id: 55, name: "Economy car" },
  { id: 56, name: "Luxury car" },
  { id: 57, name: "Truck" },
  
  // Havacılık & Uzay
  { id: 77, name: "Fuselage" },
  { id: 78, name: "Wing" },
  { id: 80, name: "Flight computer" },
  { id: 81, name: "Cockpit" },
  { id: 82, name: "Attitude control" },
  { id: 84, name: "Fuel tank" },
  { id: 85, name: "Solid rocket" },
  { id: 86, name: "Rocket engine" },
  { id: 87, name: "Heat shield" },
  { id: 88, name: "Ion drive" },
  { id: 89, name: "Jet engine" },
  { id: 90, name: "Passenger jet" },
  { id: 91, name: "Sub-orbital rocket" },
  { id: 92, name: "Cargo plane" },
  { id: 93, name: "Space probe" },
  { id: 94, name: "BFR" },
  { id: 95, name: "Cargo jet" },
  { id: 96, name: "Luxury jet" },
  { id: 97, name: "Orbital rocket" },
  { id: 99, name: "Satellite" },
  
  // Madenler & Hammaddeler
  { id: 14, name: "Minerals" },
  { id: 15, name: "Bauxite" },
  { id: 16, name: "Silicon" },
  { id: 17, name: "Chemicals" },
  { id: 18, name: "Aluminium" },
  { id: 19, name: "Plastic" },
  { id: 42, name: "Iron ore" },
  { id: 43, name: "Steel" },
  { id: 44, name: "Sand" },
  { id: 45, name: "Glass" },
  { id: 68, name: "Gold ore" },
  { id: 69, name: "Gold" },
  { id: 75, name: "Carbon fiber" },
  { id: 76, name: "Carbon composite" },
  
  // Özel Etkinlikler
  { id: 147, name: "Jack-o-lantern" },
  { id: 148, name: "Witch costume" },
  { id: 150, name: "Christmas tree" },
  { id: 67, name: "Christmas crackers" },
  { id: 144, name: "Christmas ornament" },
  { id: 151, name: "Easter bunny" },
  { id: 155, name: "Cream egg" },
  { id: 152, name: "Ramadan sweets" },
  { id: 153, name: "Ice cream chocolate" },
  { id: 154, name: "Ice cream apple" },
  
  // Araştırma
  { id: 29, name: "Plant research" },
  { id: 30, name: "Energy research" },
  { id: 31, name: "Mining research" },
  { id: 32, name: "Electronics research" },
  { id: 33, name: "Breeding research" },
  { id: 34, name: "Chemistry research" },
  { id: 58, name: "Automotive research" },
  { id: 59, name: "Fashion research" },
  { id: 100, name: "Aero research" },
  { id: 113, name: "Materials research" },
  
  // Diğer
  { id: 35, name: "Software" },
  { id: 145, name: "Recipes" },
];
